//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoyaltyViewerWpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoyaltyViewerWpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разработка приложения:
        ///ООО &quot;Клиника ЛМС&quot;
        ///dev@bzklinika.ru.
        /// </summary>
        public static string AboutDeveloper {
            get {
                return ResourceManager.GetString("AboutDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Терминал расположен в холле клиники.
        /// </summary>
        public static string AboutSubTitle {
            get {
                return ResourceManager.GetString("AboutSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просим Вас уделить пару минут и оценить нашу работу.
        /// </summary>
        public static string AboutTItle {
            get {
                return ResourceManager.GetString("AboutTItle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сегодня поставлено
        ///оценок:.
        /// </summary>
        public static string DoctorsMarksLabelToday {
            get {
                return ResourceManager.GetString("DoctorsMarksLabelToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вчера поставлено
        ///оценок:.
        /// </summary>
        public static string DoctorsMarksLabelYesterday {
            get {
                return ResourceManager.GetString("DoctorsMarksLabelYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franklin Gothic Book.
        /// </summary>
        public static string FontFamilyMain {
            get {
                return ResourceManager.GetString("FontFamilyMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению, сейчас нет доступных для записи мест..
        /// </summary>
        public static string PromoJustNowNothingToShow {
            get {
                return ResourceManager.GetString("PromoJustNowNothingToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Скидка предоставляется только при записи за наличный расчет и не суммируется с другими действующими акциями, скидками и специальными предложениями. Запись на приём осуществляется только через регистратуру Клиники в день приёма, не позднее, чем за 1,5 часа до начала. Список отделений, участвующих в акции, ограничен.
        ///Подробности Вы можете узнать на регистратуре..
        /// </summary>
        public static string PromoJustNowSubtitle {
            get {
                return ResourceManager.GetString("PromoJustNowSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сегодня
        ///проголосовало пациентов:.
        /// </summary>
        public static string RecommendationLabelToday {
            get {
                return ResourceManager.GetString("RecommendationLabelToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вчера
        ///проголосовало пациентов:.
        /// </summary>
        public static string RecommendationLabelYesterday {
            get {
                return ResourceManager.GetString("RecommendationLabelYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нам важно Ваше мнение о нас.
        /// </summary>
        public static string WindowMainTitleAbout {
            get {
                return ResourceManager.GetString("WindowMainTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рекомендации нашей клиники.
        /// </summary>
        public static string WindowMainTitleClinicRecommendations {
            get {
                return ResourceManager.GetString("WindowMainTitleClinicRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мнение пациентов о работе наших врачей.
        /// </summary>
        public static string WindowMainTitleDoctorsMarks {
            get {
                return ResourceManager.GetString("WindowMainTitleDoctorsMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только сейчас - скидка 30% на приём*.
        /// </summary>
        public static string WindowMainTItlePromoJustNow {
            get {
                return ResourceManager.GetString("WindowMainTItlePromoJustNow", resourceCulture);
            }
        }
    }
}
