//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoyaltyViewerWpf.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoyaltyViewerWpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разработка приложения:
        ///ООО &quot;Клиника ЛМС&quot;
        ///dev@bzklinika.ru.
        /// </summary>
        public static string AboutDeveloper {
            get {
                return ResourceManager.GetString("AboutDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Терминал расположен в холле клиники.
        /// </summary>
        public static string AboutSubTitle {
            get {
                return ResourceManager.GetString("AboutSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просим Вас уделить пару минут и оценить качество нашей работы.
        /// </summary>
        public static string AboutTItle {
            get {
                return ResourceManager.GetString("AboutTItle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сегодня поставлено
        ///оценок:.
        /// </summary>
        public static string DoctorsMarksLabelToday {
            get {
                return ResourceManager.GetString("DoctorsMarksLabelToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вчера поставлено
        ///оценок:.
        /// </summary>
        public static string DoctorsMarksLabelYesterday {
            get {
                return ResourceManager.GetString("DoctorsMarksLabelYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Franklin Gothic Book.
        /// </summary>
        public static string FontFamilyMain {
            get {
                return ResourceManager.GetString("FontFamilyMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на *Скидка предоставляется только при записи за наличный расчет и не суммируется с другими акциями..
        /// </summary>
        public static string PromoJustNowSubtitle {
            get {
                return ResourceManager.GetString("PromoJustNowSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сегодня
        ///проголосовало пациентов:.
        /// </summary>
        public static string RecommendationLabelToday {
            get {
                return ResourceManager.GetString("RecommendationLabelToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вчера
        ///проголосовало пациентов:.
        /// </summary>
        public static string RecommendationLabelYesterday {
            get {
                return ResourceManager.GetString("RecommendationLabelYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нам важно Ваше мнение о нас.
        /// </summary>
        public static string WindowMainTitleAbout {
            get {
                return ResourceManager.GetString("WindowMainTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рекомендации нашей клиники.
        /// </summary>
        public static string WindowMainTitleClinicRecommendations {
            get {
                return ResourceManager.GetString("WindowMainTitleClinicRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мнение пациентов о работе наших врачей.
        /// </summary>
        public static string WindowMainTitleDoctorsMarks {
            get {
                return ResourceManager.GetString("WindowMainTitleDoctorsMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только сейчас - скидка 30% на приём*.
        /// </summary>
        public static string WindowMainTItlePromoJustNow {
            get {
                return ResourceManager.GetString("WindowMainTItlePromoJustNow", resourceCulture);
            }
        }
    }
}
